test_model:
  n_recs: 10

userknn_model:
  n_recs: 10
  online_mode: False
  online: 'service/reco_models/userknn_model.dill'
  offline: 'data/userknn_recos.csv'

popular_model:
  n_recs: 10
  online: 'service/reco_models/popular_model.dill'
  offline: 'data/popular_recos.csv'
