userknn_model:
  online_mode: True
  online: 'data/userknn_model.dill'
  offline: 'data/userknn_recos.csv'

popular_model:
  online: 'data/popular_model.dill'
  offline: 'data/popular_recos.csv'

lightfm_model:
  online: 'data/lightfm_model.dill'
