# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2022-11-20T18:06:42+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel, Field


class Error(BaseModel):
    error_key: str = Field(..., title="Error Key")
    error_message: str = Field(..., title="Error Message")
    error_loc: Optional[Any] = None


class UnauthorizedError(BaseModel):
    error_key: str = Field(..., title="Error Key")
    error_message: str = Field(..., title="Error Message")
    error_loc: Optional[List[str]] = Field(None, title="Error Location")


class ForbiddenError(BaseModel):
    error_key: str = Field(..., title="Error Key")
    error_message: str = Field(..., title="Error Message")
    error_loc: Optional[List[str]] = Field(None, title="Error Location")


class NotFoundError(BaseModel):
    error_key: str = Field(..., title="Error Key")
    error_message: str = Field(..., title="Error Message")
    error_loc: Optional[List[str]] = Field(None, title="Error Location")


class ValidationError(BaseModel):
    error_key: str = Field(..., title="Error Key")
    error_message: str = Field(..., title="Error Message")
    error_loc: Optional[List[str]] = Field(None, title="Error Location")


class RecoResponse(BaseModel):
    user_id: int = Field(..., title="User Id")
    items: List[int] = Field(..., title="Items")

    class Config:
        schema_extra = {"example": {"user_id": 4456, "items": [12, 13, 123, 124, 24, 35, 67, 56, 89, 23]}}


class HealthResponse(BaseModel):
    health: str = Field(..., title="Health")

    class Config:
        schema_extra = {"example": {"health": "I am alive. Everything is OK!"}}


class HTTPValidationError(BaseModel):
    detail: Optional[List[ValidationError]] = Field(None, title="Validation Error")
