UserKnn_model_conf:
    model: TFIDFRecommender()
    save_reco_df_path: 'data/offline_recs_df/userknn_TFIDF.dill'
    dataset_path: 'data/kion_train/userknn_recs'
    N_recs: 10
    online: False
    blend_threshold: 3
    n_folds: 3
    unit: "D"
    n_units: 4
    periods: 2
    dataset_path: 'data/kion_train'


Popular_model_conf:
    save_reco_df_path: 'data/offline_recs_df/popular'
    dataset_path: 'data/kion_train'
    N_recs: 10


ALS_model_conf:
    save_reco_df_path: 'data/offline_recs_df/als'


SVD_model_conf:
    save_reco_df_path: 'data/offline_recs_df/svd'


LightFM_model_conf:
    save_reco_df_path: 'data/offline_recs_df/lightfm'


ANN_model_conf:
    label: 'data/offline_recs_df/ANN_label.sav'
    distance: 'data/offline_recs_df/ANN_distance.sav'
