name: Service testing
on: [push, pull_request]


jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Install dev requirements
        run: pip install -r requirements-dev.txt

      - name: "Run tests"
        run: pytest -vv tests/
